#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

$POSTGRES <<EOSQL
CREATE DATABASE ${DB_BASE} OWNER ${POSTGRES_USER};
CREATE DATABASE ${DB_AUTH} OWNER ${POSTGRES_USER};
CREATE DATABASE ${DB_COMPETITION} OWNER ${POSTGRES_USER};
EOSQL